import Head from "next/head";
import { Inter } from "@next/font/google";
import Footer from "../components/footer/Footer";
import Banner from "../components/banner/Banner";
import Header from "../components/header/Header";
import ScreenShots from "../components/screenshots/Screenshots";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | The Blue Roof</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed top-0 w-full z-100">
        <Header />
      </div>
      <Banner />
      <ScreenShots />
      <Footer />
    </>
  );
}
